### ISSUE TITLE
how to simple use existing plugins?

### ISSUE THREAD

**Issue by LYY1220** [IGNF/CartAGen#25]
I recently read  the  paper "CartAGen: an Open Source Research Platform for Map Generalization". In the use part，I have some questions. how we can a simple access  to its functionalities? For example:  few existing plugins mentioned in the paper is exsit? 
Is there any other simple use the CartAgen?  In my project, license issues maybe prevent me from downloading some packages.

**Comment by gtouya** [comment]
I am not really sure to understand the question. Do you want to use the functionalities? Or do you want to access them via Java code, from another Java platform? If it is the first case, you can simply use the GUI as explained in the documentation. If it is the second case, you can use the library with Maven. The license is the French equivalent of LGPL, so you can use it in any other platform. The only GPL dependency is the C triangulation, so you might need to tweek the triangulation code to rather use the one from JTS.
Does that answer your question?

**Comment by huanghesheng2012** [comment]
as mentioned above, "you can simply use the GUI as explained in the documentation", how do I find the documentation to start the GUI of this java project? I downloaded the code package, but I got an error when compiling cartagen-appli under CartAGen-master using eclipse, saying:
Reactor Summary for cartagen 0.1-SNAPSHOT:[m]
[INFO]
[INFO] cartagen ...........................................   [1; 33 mskipped  [m
[INFO] cartagen-core ......................................   [1; 33 mskipped  [m
[INFO] cartagen-appli .....................................   [1; 33 mskipped  [m
[the INFO]  [1 m -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --  [m
[INFO] [1;31mBUILD FAILURE[m]
[the INFO]  [1 m -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --  [m
[INFO] Total time: 0.144s
[INFO] Finished at: 2024-09-09T19:36:13+08:00
[the INFO]  [1 m -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --  [m
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format  <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases  are:  pre-clean, clean, post-clean, validate, initialize, generate-sources, process-sources, generate-resources,  process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources,  process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test,  integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site,  site-deploy. -> [1m[Help 1][m
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the [1m-e] [m switch.
[ERROR] Re-run Maven using the [1m-X] [m switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR]  [1 m [1] Help  [m http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException，，以上翻译结果来自有道神经网络翻译（YNMT）· 通用场景

逐句对照
AI润色

**Comment by huanghesheng2012** [comment]
I used the import function of eclipse to clone this Maven java package from github, the mouse click on the run-Maven build, reported an error...
The error message is as follows:
[INFO] cartagen ...........................................  [1;32mSUCCESS[m [0.213s]
[INFO] cartagen-core ......................................  [1;31mFAILURE[m [1.018s]
[INFO] cartagen-appli .....................................   [1; 33 mskipped  [m
[the INFO]  [1 m -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --  [m
[INFO] [1;31mBUILD FAILURE[m]
[the INFO]  [1 m -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --  [m
[INFO] Total time: 1.383s
[INFO] Finished at: 2024-09-10T07:36:44+08:00
[the INFO]  [1 m -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --  [m
[ERROR] Failed to execute goal on project [36mcartagen-core] [m: [1;31mCould not resolve dependencies for project fr.ign.cogit:cartagen-core:jar:0.1-SNAPSHOT: The following artifacts could not be resolved:  fr.ign.cogit:geoxygene-osm:jar: 1.10-snapshot (absent), fr.ign.cogit:geoxygene-util:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-api:jar: 1.10-snapshot (absent), fr.ign.cogit:geoxygene-schemageo:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-feature:jar: geoxygene-spatial:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-spatial:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-io:jar: geoxygene-filter:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-filter:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-style:jar: geoxygene-contrib:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-contrib:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-database:jar:1.10-SNAPSHOT (absent), Fr. Ign. Cogit: geoxygene - spatialrelation: jar: 1.10 the SNAPSHOT (absent), org. Semanticweb: owlapi: jar: 3.0.0 (absent). Twak: campskeleton: jar: 1.0 (absent) : fr.ign.cogit:geoxygene-osm:jar:1.10-SNAPSHOT was not found in the snapshot file://D:\mapgeneralization\DeepLearningforMap\git\CartAgen2\CartAGen\cartagen-core/local-maven-repo during a previous  attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of  local-maven-repo has elapsed or updates are forced[m -> [1m[Help 1][m]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the [1m-e] [m switch.
[ERROR] Re-run Maven using the [1m-X] [m switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR]  [1 m [1] Help  [m http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] [1mmvn <args> -rf :cartagen-core[m]

**Comment by huanghesheng2012** [comment]
the key error is:
Failed to execute goal on project [36mcartagen-core[m: [1;31mCould not resolve dependencies for project fr.ign.cogit:cartagen-core:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: fr.ign.cogit:geoxygene-osm:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-util:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-api:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-schemageo:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-feature:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-spatial:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-io:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-filter:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-style:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-contrib:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-database:jar:1.10-SNAPSHOT (absent), fr.ign.cogit:geoxygene-spatialrelation:jar:1.10-SNAPSHOT (absent), org.semanticweb:owlapi:jar:3.0.0 (absent), twak:campskeleton:jar:1.0 (absent): fr.ign.cogit:geoxygene-osm:jar:1.10-SNAPSHOT was not found in file://D:\mapgeneralization\DeepLearningforMap\git\CartAgen2\CartAGen\cartagen-core/local-maven-repo during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of local-maven-repo has elapsed or updates are forced[m -> [1m[Help 1]

**Comment by gtouya** [comment]
It looks like you misconfigured your local maven repository.
Unfortunately, I cannot help you more because this project is no longer maintained. We switched to a Python version (https://cartagen.readthedocs.io/en/latest/) where we can provide some support.
